"use strict";

const CASHFREE_PAYMENT_STATUS = {
  ACTIVE: "ACTIVE",
  PAID: "PAID",
  EXPIRED: "EXPIRED",
  TERMINATED: "TERMINATED",
  FAILED: "FAILED",
  USER_DROPPED: "USER_DROPPED"
};

module.exports = {
  CASHFREE_PAYMENT_STATUS
};
